services:
  app1:
    build: .
    environment:
      - APP_NAME=App1
    expose:
      - "3000"

  app2:
    build: .
    environment:
      - APP_NAME=App2
    expose:
      - "3000"

  app3:
    build: .
    environment:
      - APP_NAME=App3
    expose:
      - "3000"

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
      - app3

